import streamlit as st
import pandas as pd
import sqlite3
import os

st.title("SQLite Database Viewer")

db_file = st.file_uploader("Upload your SQLite database", type=['db', 'sqlite', 'sqlite3'])

if db_file:
    # Save uploaded file temporarily
    temp_path = f"temp_{db_file.name}"
    with open(temp_path, 'wb') as f:
        f.write(db_file.getbuffer())

    try:
        conn = sqlite3.connect(temp_path)

        # Get all tables
        tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)

        if tables.empty:
            st.warning("No tables found in this database.")
        else:
            table_list = tables['name'].tolist()
            st.success(f"Found {len(table_list)} table(s): {', '.join(table_list)}")

            selected_table = st.selectbox("Select a table", options=table_list)

            if selected_table:
                df = pd.read_sql(f"SELECT * FROM '{selected_table}'", conn)

                # Stats row
                col1, col2, col3 = st.columns(3)
                col1.metric("Rows", df.shape[0])
                col2.metric("Columns", df.shape[1])
                col3.metric("Null Values", int(df.isnull().sum().sum()))

                # Search / filter
                search = st.text_input("Filter rows (searches all columns)", placeholder="Type to filter...")
                if search:
                    mask = df.apply(lambda col: col.astype(str).str.contains(search, case=False, na=False)).any(axis=1)
                    df = df[mask]
                    st.caption(f"{len(df)} rows match '{search}'")

                st.dataframe(df, use_container_width=True)

                # Column info
                with st.expander("Column Info"):
                    info = pd.DataFrame({
                        'Column': df.columns,
                        'Type': df.dtypes.values,
                        'Non-Null': df.notnull().sum().values,
                        'Null': df.isnull().sum().values,
                        'Unique': df.nunique().values,
                    })
                    st.dataframe(info, use_container_width=True)

                # Summary stats
                with st.expander("Summary Statistics"):
                    st.dataframe(df.describe(), use_container_width=True)

                # Custom SQL
                with st.expander("Run Custom SQL"):
                    query = st.text_area("SQL Query", value=f"SELECT * FROM '{selected_table}' LIMIT 10")
                    if st.button("Run Query"):
                        try:
                            result = pd.read_sql(query, conn)
                            st.dataframe(result, use_container_width=True)
                        except Exception as e:
                            st.error(f"Query error: {e}")

                # Download
                st.markdown("---")
                download_format = st.selectbox("Download as", ['csv', 'json'])
                if download_format == 'csv':
                    data = df.to_csv(index=False)
                    mime = 'text/csv'
                    fname = f"{selected_table}.csv"
                else:
                    data = df.to_json(orient='records', indent=2)
                    mime = 'application/json'
                    fname = f"{selected_table}.json"

                st.download_button(f"Download as {download_format.upper()}", data=data, file_name=fname, mime=mime)

        conn.close()

    except Exception as e:
        st.error(f"Could not read database: {e}")

    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

else:
    st.info("Upload a `.db` file to get started. This works with the `pipeline.db` generated by the ETL pipeline.")
